# Generated by Django 4.1.3 on 2022-12-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('baja', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEje', models.CharField(default='eje1', max_length=50, verbose_name='nombreEje')),
                ('descripcion', models.TextField(null=True, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('dni', models.IntegerField(verbose_name='dni')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha_de_creacion')),
                ('estado', models.IntegerField(choices=[(1, 'Inscripto'), (2, 'Cursando'), (3, 'Egresado')], default=1)),
                ('ejes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educ.eje')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educ.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ejes',
            field=models.ManyToManyField(through='educ.Inscripcion', to='educ.eje'),
        ),
    ]
