# Generated by Django 4.1.3 on 2022-12-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eje',
            old_name='nombreEje',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha',
            field=models.DateField(null=True, verbose_name='fecha_de_creacion'),
        ),
    ]
