# Generated by Django 4.1.3 on 2022-12-12 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educ', '0002_rename_nombreeje_eje_nombre_alter_inscripcion_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eje',
            options={'verbose_name_plural': 'Eje'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name_plural': 'Estudiante'},
        ),
        migrations.AddField(
            model_name='eje',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='educ.categoria'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='baja',
            field=models.BooleanField(default='False'),
        ),
    ]
